/* DO NOT EDIT, file generated by @productdevbook/ts-i18n */

import { Path } from "@productdevbook/ts-i18n";
export type I18nTranslations = {
    "hello": string;
    "hi_name_welcome_to_place": string;
    "name_your_name_is_name": string;
    "empty_string": string;
};
export type I18nPath = Path<I18nTranslations>;
