/* DO NOT EDIT, file generated by @productdevbook/ts-i18n */
/* eslint-disable */
/* prettier-ignore */
// @ts-ignore

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "hello": string;
    "hi_name_welcome_to_place": {
        "variables": {
            "name": string;
            "place": string;
        };
    };
    "name_your_name_is_name": {
        "variables": {
            "name": string;
            "name": string;
        };
    };
    "empty_string": string;
};
export type I18nPath = Path<I18nTranslations>;
