/* DO NOT EDIT, file generated by @productdevbook/ts-i18n */

import { Path } from "@productdevbook/ts-i18n";
export type I18nTranslations = {
    "hello": string;
    "foo": string;
    "headeraaa": {
        "x-foo": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
