/* DO NOT EDIT, file generated by @productdevbook/ts-i18n */
/* eslint-disable */
/* prettier-ignore */
// @ts-ignore

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "hello": string;
    "foo": string;
    "hello2": string;
    "headeraaa": {
        "x-foo": {
            "variables": {
                "tttt": string;
                "bbb": string;
            };
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
